name: "Git Repo Mirror"
author: "Gautham Prakash <gautham.p@exlygenze.com>"
description: "Fork of Universal mirroring repository tool. (pkgstore)"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  source_repo:
    description: "Source Repository"
    required: true
  source_user:
    description: "Source User"
    required: true
  source_token:
    description: "Source Token"
    required: true
  target_repo:
    description: "Target Repository"
    required: true
  target_user:
    description: "Target User"
    required: true
  target_token:
    description: "Target Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.source_user }}
    - ${{ inputs.source_token }}
    - ${{ inputs.target_repo }}
    - ${{ inputs.target_user }}
    - ${{ inputs.target_token }}
